[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
dotenvy = "0.15.7"
sea-orm = { version = "1.1.12", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros"
] }
tokio = { version = "1.45.0", features = ["full"] }